dist: trusty
sudo: required

language: python
python: "3.5"
install:
  pip install -r requirements.txt

addons:
  sonarcloud:
    organization: "laujorpan"
    token:
      secure: "fc2941c5d795ecf55fe89dff1980221be7fa79b2"
    github_token:
      secure: "fc2941c5d795ecf55fe89dff1980221be7fa79b2"
    branches:
      - develop
      - master

script:
  sonar-scanner
cache:
  directories:
    '$HOME/.sonar/cache'